//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIO
    {
        public string EMP_ID { get; set; }
        public Nullable<System.DateTime> I_DT { get; set; }
        public Nullable<System.DateTime> O_DT { get; set; }
        public Nullable<System.DateTime> ATT_DATE { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
