//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EM()
        {
            this.CTTMSTs = new HashSet<CTTMST>();
            this.PROMDTLs = new HashSet<PROMDTL>();
            this.EMDTLs = new HashSet<EMDTL>();
            this.EMDTL1 = new HashSet<EMDTL1>();
            this.EMDTL2 = new HashSet<EMDTL2>();
            this.FEECOLLECTMSTs = new HashSet<FEECOLLECTMST>();
            this.LEAVECERTMSTs = new HashSet<LEAVECERTMST>();
            this.MARKSDTLs = new HashSet<MARKSDTL>();
            this.SECCHANGEs = new HashSet<SECCHANGE>();
            this.SPFEEDTLs = new HashSet<SPFEEDTL>();
        }
    
        public double TRNNO { get; set; }
        public string EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<double> CST_TRNNO { get; set; }
        public string EMP_F_NAME { get; set; }
        public Nullable<double> COMP_TRNNO { get; set; }
        public Nullable<double> BP_TRNNO { get; set; }
        public string ETYPE { get; set; }
        public Nullable<double> CL_TRNNO { get; set; }
        public Nullable<double> CL_TRNNO1 { get; set; }
        public string CERTIFICATE { get; set; }
        public Nullable<System.DateTime> PSCHDT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> ADT { get; set; }
        public string FTYPE { get; set; }
        public Nullable<double> FEE { get; set; }
        public string EMAILST { get; set; }
        public Nullable<double> GRPMST_TRNNO { get; set; }
        public string CNIC { get; set; }
        public Nullable<double> SECMST_TRNNO { get; set; }
        public Nullable<double> SECDTL_SR { get; set; }
        public string SEX { get; set; }
        public Nullable<double> BSAL { get; set; }
        public string FCNIC { get; set; }
        public Nullable<double> ADIMNO { get; set; }
        public string STYPE { get; set; }
    
        public virtual CST CST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTMST> CTTMSTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROMDTL> PROMDTLs { get; set; }
        public virtual SECMST SECMST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMDTL> EMDTLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMDTL1> EMDTL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMDTL2> EMDTL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEECOLLECTMST> FEECOLLECTMSTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAVECERTMST> LEAVECERTMSTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKSDTL> MARKSDTLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECCHANGE> SECCHANGEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPFEEDTL> SPFEEDTLs { get; set; }
    }
}
