//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMDTL2
    {
        public double TRNNO { get; set; }
        public double SR { get; set; }
        public Nullable<double> EDU_TRNNO { get; set; }
        public string PTYPE { get; set; }
        public string YEAR { get; set; }
        public string GRD { get; set; }
        public Nullable<double> PERCENT { get; set; }
    
        public virtual EDUCATION EDUCATION { get; set; }
        public virtual EM EM { get; set; }
    }
}
