//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMDTL1
    {
        public double TRNNO { get; set; }
        public double SR { get; set; }
        public string PHNO { get; set; }
        public string PHTYPE { get; set; }
        public Nullable<double> RELTION { get; set; }
    
        public virtual EM EM { get; set; }
    }
}
