//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEECOLLECTMST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FEECOLLECTMST()
        {
            this.FEECOLLECTDTLs = new HashSet<FEECOLLECTDTL>();
        }
    
        public double TRNNO { get; set; }
        public Nullable<System.DateTime> RDATE { get; set; }
        public Nullable<double> EM_TRNNO { get; set; }
        public Nullable<double> FMONTH { get; set; }
        public Nullable<System.DateTime> DDATE { get; set; }
        public Nullable<System.DateTime> LDATE { get; set; }
        public string FSTATUS { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public string DISCOUNTTYPE { get; set; }
        public Nullable<double> CLASS_TRNNO { get; set; }
        public Nullable<double> SECDTL_TRNNO { get; set; }
        public Nullable<double> SECDTL_SR { get; set; }
        public Nullable<System.DateTime> PDATE { get; set; }
        public Nullable<double> ARRFLG { get; set; }
    
        public virtual EM EM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEECOLLECTDTL> FEECOLLECTDTLs { get; set; }
    }
}
