//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISCAL_YEAR
    {
        public double TRNNO { get; set; }
        public Nullable<System.DateTime> FDATE { get; set; }
        public Nullable<System.DateTime> TDATE { get; set; }
        public string YEAR_DESC { get; set; }
        public string ACTIVE { get; set; }
    }
}
