//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRPDTL
    {
        public double TRNNO { get; set; }
        public double SUBJECT_TRNNO { get; set; }
        public int ID { get; set; }
    
        public virtual GRPMST GRPMST { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
