//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRPMST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRPMST()
        {
            this.GRPDTLs = new HashSet<GRPDTL>();
            this.MARKSMSTOLDs = new HashSet<MARKSMSTOLD>();
            this.PROMMSTs = new HashSet<PROMMST>();
        }
    
        public double TRNNO { get; set; }
        public string GRPNAME { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<double> COMPDTL_TRNNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRPDTL> GRPDTLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKSMSTOLD> MARKSMSTOLDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROMMST> PROMMSTs { get; set; }
    }
}
