//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKSDTL
    {
        public double TRNNO { get; set; }
        public double SR { get; set; }
        public Nullable<double> EM_TRNNO { get; set; }
        public int Id { get; set; }
    
        public virtual EM EM { get; set; }
        public virtual MARKSMST MARKSMST { get; set; }
    }
}
