//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKTOTALDTL
    {
        public double TRNNO { get; set; }
        public double SR { get; set; }
        public Nullable<double> SUBJECT_TRNNO { get; set; }
        public double TOTMARKS { get; set; }
    
        public virtual MARKTOTAL MARKTOTAL { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
