//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKSMSTOLD
    {
        public double TRNNO { get; set; }
        public Nullable<System.DateTime> MDT { get; set; }
        public Nullable<double> EXAM_TRNNO { get; set; }
        public Nullable<double> CLASS_TRNNO { get; set; }
        public Nullable<double> GRPMST_TRNNO { get; set; }
        public Nullable<double> EM_TRNNO { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual GRPMST GRPMST { get; set; }
    }
}
