//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKSDTL1
    {
        public double TRNNO { get; set; }
        public double SR { get; set; }
        public double SR1 { get; set; }
        public Nullable<double> GMARKS { get; set; }
        public Nullable<double> MARKTOTALDTL_TRNNO { get; set; }
        public Nullable<double> MARKTOTALDTL_SR { get; set; }
    
        public virtual MARKSDTL MARKSDTL { get; set; }
    }
}
