//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public double Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> STATUS { get; set; }
    }
}
